
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 10 00:19:00 CST 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PUNTO1 = 19;
  public static final int Conjunto = 4;
  public static final int OR = 21;
  public static final int SUMA = 22;
  public static final int Comilla_s = 10;
  public static final int Mayor = 6;
  public static final int CON = 18;
  public static final int ERROR = 9;
  public static final int Identificador = 8;
  public static final int Llave_c = 3;
  public static final int COMILLAS = 16;
  public static final int Llave_a = 2;
  public static final int Com2 = 12;
  public static final int Oracion2 = 24;
  public static final int KLEENE = 20;
  public static final int Com1 = 11;
  public static final int P_coma = 13;
  public static final int Oracion = 23;
  public static final int EOF = 0;
  public static final int Interrogacion = 17;
  public static final int D_puntos = 7;
  public static final int error = 1;
  public static final int Porcentaje = 15;
  public static final int Guion = 5;
  public static final int Barra = 14;
}

