
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 24 01:17:52 CST 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PUNTO1 = 21;
  public static final int Conjunto = 4;
  public static final int OR = 23;
  public static final int CON1 = 5;
  public static final int SUMA = 24;
  public static final int Comilla_s = 12;
  public static final int Mayor = 8;
  public static final int CON = 20;
  public static final int ERROR = 11;
  public static final int Identificador = 10;
  public static final int Llave_c = 3;
  public static final int COMILLAS = 18;
  public static final int Com3 = 7;
  public static final int Llave_a = 2;
  public static final int Com2 = 14;
  public static final int Oracion2 = 26;
  public static final int KLEENE = 22;
  public static final int Com1 = 13;
  public static final int P_coma = 15;
  public static final int Oracion = 25;
  public static final int EOF = 0;
  public static final int Interrogacion = 19;
  public static final int D_puntos = 9;
  public static final int Porcentaje = 17;
  public static final int error = 1;
  public static final int Guion = 6;
  public static final int Barra = 16;
}

