
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 02 22:38:33 CST 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PUNTO1 = 16;
  public static final int Conjunto = 4;
  public static final int OR = 18;
  public static final int SUMA = 19;
  public static final int Comilla_s = 10;
  public static final int Mayor = 6;
  public static final int CON = 15;
  public static final int ERROR = 9;
  public static final int Identificador = 8;
  public static final int Llave_c = 3;
  public static final int COMILLAS = 13;
  public static final int Llave_a = 2;
  public static final int Oracion2 = 21;
  public static final int KLEENE = 17;
  public static final int P_coma = 11;
  public static final int Oracion = 20;
  public static final int EOF = 0;
  public static final int Interrogacion = 14;
  public static final int D_puntos = 7;
  public static final int error = 1;
  public static final int Porcentaje = 12;
  public static final int Guion = 5;
}

